import com.ruleEngine.drools.demo.dto.*;

rule "If customer type is regular and quantity [76-100] , Set Price as 20"
when
    $product:Product(item=='apple' && customerType=='regular' && quantity>=76 && quantity<=100)
then
    $product.setCost(20);
end

rule "If customer type is premium and quantity [76-100] , Set Price as 15"
when
    $product:Product(item=='apple' && customerType=='premium' && quantity>=76 && quantity<=100)
then
    $product.setCost(15);
end


rule "If customer type is regular and quantity [51-75] , Set Price as 22"
when
    $product:Product(item=='apple' && customerType=='regular' && quantity>=51 && quantity<=75)
then
    $product.setCost(22);
end


rule "If customer type is premium and quantity [51-75] , Set Price as 17"
when
    $product:Product(item=='apple' && customerType=='premium' && quantity>=51 && quantity<=75)
then
    $product.setCost(17);
end


rule "If customer type is regular and quantity [1-50] , Set Price as 24"
when
    $product:Product(item=='apple' && customerType=='regular' && quantity>=1 && quantity<=50)
then
    $product.setCost(24);
end


rule "If customer type is premium and quantity [1-50] , Set Price as 20"
when
    $product:Product(item=='apple' && customerType=='premium' && quantity>=1 && quantity<=50)
then
    $product.setCost(20);
end


