import com.ruleEngine.drools.demo.dto.*;

rule "If customer type is regular and quantity [76-100] , Set Price as 10"
when
    $product:Product(item=='apple' && customerType=='regular' && available>=76 && available<=100)
then
    $product.setCost(10);
end

rule "If customer type is premium and quantity [76-100] , Set Price as 8"
when
    $product:Product(item=='apple' && customerType=='premium' && available>=76 && available<=100)
then
    $product.setCost(8);
end


rule "If customer type is regular and quantity [51-75] , Set Price as 12"
when
    $product:Product(item=='apple' && customerType=='regular' && available>=51 && available<=75)
then
    $product.setCost(12);
end


rule "If customer type is premium and quantity [51-75] , Set Price as 10"
when
    $product:Product(item=='apple' && customerType=='premium' && available>=51 && available<=75)
then
    $product.setCost(10);
end


rule "If customer type is regular and quantity [1-50] , Set Price as 14"
when
    $product:Product(item=='apple' && customerType=='regular' && available>=1 && available<=50)
then
    $product.setCost(14);
end


rule "If customer type is premium and quantity [1-50] , Set Price as 11"
when
    $product:Product(item=='apple' && customerType=='premium' && available>=1 && available<=50)
then
    $product.setCost(11);
end


